name = "snow"
description = "Console output utilities"
version = "1.0.0"

authors = ["Navid M"]
maintainers = ["Navid M <navidm@navidm.com>"]
maintainers-logins = ["navidm"]
licenses = "GPL-3.0-only"
website = "https://github.com/navid-m/snow"
tags = ["cli", "console", "output", "utilities"]
