name = "snow"
description = "Console output utilities"
version = "0.1.0-dev"

authors = ["Navid M"]
maintainers = ["Navid M <example@example.com>"]
licenses = "GPL-3.0-only"
website = "https://github.com/navid-m/snow"
tags = []
